# Generated by Django 2.1.3 on 2018-12-04 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('description', models.TextField(default='Description is unknown', max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(max_length=1000)),
                ('user', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50)),
                ('year_of_release', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(0)])),
                ('country', models.CharField(default='Unknown', max_length=20)),
                ('description', models.TextField(default='This description is not added yet', max_length=500)),
                ('poster', models.CharField(default='images/unknown.png', max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('actors', models.ManyToManyField(to='todo.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('film_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Film')),
            ],
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='todo.Genre'),
        ),
        migrations.AddField(
            model_name='comment',
            name='film_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Film'),
        ),
    ]
