# Generated by Django 2.1.3 on 2018-12-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181204_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres_name',
            new_name='genre_name',
        ),
    ]
