# Generated by Django 2.1.3 on 2018-12-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_actor_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image_link1',
            field=models.CharField(default='images/unknown.png', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='image_link2',
            field=models.CharField(default='images/unknown.png', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='image_link3',
            field=models.CharField(default='images/unknown.png', max_length=50),
        ),
    ]
