# Generated by Django 2.1.3 on 2018-12-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20181205_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image_link',
            field=models.CharField(default='https://vignette.wikia.nocookie.net/kongregate/images/9/96/Unknown_flag.png/revision/latest?cb=20100825093317', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_link1',
            field=models.CharField(default='https://vignette.wikia.nocookie.net/kongregate/images/9/96/Unknown_flag.png/revision/latest?cb=20100825093317', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_link2',
            field=models.CharField(default='https://vignette.wikia.nocookie.net/kongregate/images/9/96/Unknown_flag.png/revision/latest?cb=20100825093317', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_link3',
            field=models.CharField(default='https://vignette.wikia.nocookie.net/kongregate/images/9/96/Unknown_flag.png/revision/latest?cb=20100825093317', max_length=50),
        ),
    ]
